### ISSUE TITLE
Alimentazione dati e anagrafica

### ISSUE THREAD

**Issue by Sdipriolo** [ARPASMR/IRIS_lombardia#12]
- [x] Nivometri. Verificare alimentazione dati.

- [x] Valutare se tenere i dati dell'ultima settimana o 10 gg o 2 settimane. Automatizzare il mantenimento di tale intervallo, cancellando i dati precedenti. PASSARE a 60 gg

- [x] Rimettere  le stazioni non ARPA  in anagraficasensori e verificare il caricamento delle viste.

- [x] Cancellare  sensori doppi in anagrafica.

- [ ] Simboli stazioni meteo, idro, pluvio, anemo modificare in rete fiduciaria e non?

- [ ]  <del>Mantenere possibilità di scaricamento dati storici stazioni meccaniche</del>

- [x] Aggiungere layer aree d'allerta

- [x] Aggiungere layer fiumi, laghi, portate in tempo reale, scale di deflusso, comuni  (va studiata) e confine regionale.

**Comment by mauromussin** [comment]
Aggiornato l'elenco di spunta al 30/01/2018

**Comment by mauromussin** [comment]
Eliminato per portare l'attività in Release 1

**Comment by mauromussin** [comment]
Mi sembra esaurito l'elenco: chiudo.
