### ISSUE TITLE
funziona cerca per

### ISSUE THREAD

**Issue by mauromussin** [ARPASMR/IRIS_lombardia#41]

**Comment by armagaet** [comment]
Ciao Mauro questa issue esattamente a cosa si riferisce?

**Comment by mauromussin** [comment]
alla funzionalità di ricerca per feature geografica (comune, bacino, ecc.): forse conviene precisare quale dev'essere l'insieme minimo di feature cercabili

**Comment by antiocovargiu** [comment]
La ricerca per feature geografica agisce sui layer disponibili: una volta selezionato il layer (il più generico è Rete complessiva Arpa, il più mirato è la grandezza osservata), si ricerca la particolare feature.
