### ISSUE TITLE
RADAR: scala colore

### ISSUE THREAD

**Issue by mauromussin** [ARPASMR/IRIS_lombardia#42]
La scala colore del radar piemonte è diversa da quella ARPA L

**Comment by antiocovargiu** [comment]
Sfruttando il file in libertario02: /home/meteo/radar/level_swiss.txt, che definisce corrispondenza tra la palette delle immagini tif prodotte da meteoswiss e l’intensità oraria della precipitazione, è stata uniformata la scala del colore in accordo con le classi definite in Iris Piemonte. La scala è stata verificata per precipitazioni deboli; sarebbe opportuno controllare la corretta corrispondenza per precipitazioni orarie maggiori di 10mm.

**Comment by antiocovargiu** [comment]
Anche per le intensità più elevate la scala di colori è corretta. Ci possono essere alcune discrepanze dovute alla riproiezione geografica o alla semi-trasparenza dei png che può modificare il colore.
