### ISSUE TITLE
Errore nel calcolo delle cumulate

### ISSUE THREAD

**Issue by mauromussin** [ARPASMR/IRIS_lombardia#46]
La Query 
```
select idsensore, count(data_e_ora), sum(misura) from m_osservazioni_tr where (idsensore=8199 or idsensore=4016) and data_e_ora between '2018-05-13 13:00' and '2018-05-14 13:00' group by idsensore 
```
produce come risultato corretto i due valori
idsensore	   count	sum
4016              137    28.8
8199              140     25.4
Mentre vengono visualizzati 29 e 3 rispettivamente.
La stessa cosa non accade sulle 12h

**Comment by mauromussin** [comment]
Possiamo chiuderla?

**Comment by Sdipriolo** [comment]
Credo proprio di sì. Comunque le riguarderò bene con Antioco perché avevamo visto che anche altre possono essere chiuse.
Sara
________________________________
Da: mauromussin <notifications@github.com>
Inviato: giovedì 8 novembre 2018 18:05:02
A: ARPASMR/IRIS_lombardia
Cc: DI PRIOLO SARA; Assign
Oggetto: Re: [ARPASMR/IRIS_lombardia] Errore nel calcolo delle cumulate (#46)


Possiamo chiuderla?

**Comment by antiocovargiu** [comment]
Non mi sembra di aver riscontrato altre anomalie sulle cumulate, se non in presenza di buchi di dati.
Inoltre per questioni grafiche le cumulate oltre 1mm vengono arrotondate all'intero più vicino (28.8 -> 29).
