### ISSUE TITLE
Temperature minima e massima

### ISSUE THREAD

**Issue by mauromussin** [ARPASMR/IRIS_lombardia#57]
Graficare le temperature minime e massime come layer

**Comment by mauromussin** [comment]
Pensare ad un modo di visualizzazione, ad esempio un contenitore di layer "estremi giornalieri" con quattro layer temperature minime, temperature massime, umidità minima, umidità massima.
Il valore rappresentato è quello del giorno in corso (dalle 00) e il popup riporta l'orario di quando è la temperatura misurata. Massima/minima media di 10 minuti.

**Comment by mazanetti** [comment]
Implementazione dei layer avvenuta per valori di temperatura minima e massima giornaliera. Riguardo l'umidità  (dopo consulto con previsori) risulta di minore importanza e forse andrebbe ad "appesantire" il menù. Nel caso ne riparliamo...
